---
title: "Fredrick's Nerdebule"
header: false
footer: false
links: false
columns: "3"
connectivityCheck: true
stylesheet:
  - "assets/custom.css"
services:
  - name: "Favorites"
    icon: "fas fa-heart"
    items:
      - name: "Home Assistant"
        logo: "assets/icons/homeassistant.png"
        subtitle: "Smart home, for silly things"
        url: "https://ha.fmlab.no"
      - name: "Firefly"
        logo: "assets/icons/firefly.svg"
        subtitle: "Personal finance"
        url: "https://firefly.fmlab.no"
      - name: "Synology DSM"
        logo: "assets/icons/dsm.png"
        subtitle: "Network storage"
        url: "https://nas.fmlab.no"
  - name: "Entertainment"
    icon: "fas fa-tv"
    items:
      - name: "Jellyfin"
        logo: "assets/icons/jellyfin.svg"
        subtitle: "Personal streaming service"
        url: "https://jellyfin.fmlab.no"
      - name: "Sonarr"
        logo: "assets/icons/sonarr.png"
        subtitle: "Fetch TV-Series"
        url: "https://sonarr.fmlab.no"
      - name: "Radarr"
        logo: "assets/icons/radarr.png"
        subtitle: "Fetch Movies"
        url: "https://radarr.fmlab.no"
  - name: "System"
    icon: "fas fa-server"
    items:
      - name: "Omada"
        logo: "assets/icons/omada.png"
        subtitle: "Omada network controller"
        url: "https://omada.fmlab.no"
      - name: "AdGuard"
        logo: "assets/icons/adguard.png"
        subtitle: "Ad-Blocker and DNS Cache"
        url: "https://prowlarr.fmlab.no"
      - name: "Traefik"
        logo: "assets/icons/traefik.png"
        subtitle: "Reverse proxy"
        url: "https://traefik.fmlab.no"
  - name: "Configuration"
    icon: "fas fa-gear"
    items:
      - name: "ArgoCD"
        logo: "assets/icons/argo.png"
        subtitle: "GitOps controller"
        url: "https://argocd.fmlab.no"
      - name: "Transmission"
        logo: "assets/icons/transmission.png"
        subtitle: "Download torrents"
        url: "https://transmission.fmlab.no"
      - name: "Prowlarr"
        logo: "assets/icons/prowlarr.png"
        subtitle: "Index manager/proxy"
        url: "https://prowlarr.fmlab.no"
  - name: "Monitoring"
    icon: "fa fa-line-chart"
    items:
      - name: "Grafana"
        logo: "assets/icons/grafana.png"
        subtitle: "Metrics dashboard"
        url: "https://grafana.fmlab.no"
      - name: "Prometheus"
        logo: "assets/icons/prometheus.svg"
        subtitle: "Metrics collector and database"
        url: "https://traefik.fmlab.no"
  - name: "Public"
    icon: "fas fa-earth-europe"
    items:
      - name: "Lychee"
        logo: "assets/icons/lychee.png"
        subtitle: "Photo Gallery"
        url: "https://photos.fmlab.no"