version: '3.5'

networks:
  traefik-servicenet:
    external: true
    name: traefik-servicenet
  yarr_internal:
    driver: bridge
    internal: true

volumes:
  transmission:
  sonarr:

services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - TZ=Europe/Oslo
      - PUID=2003
      - PGID=2003
      - PEERPORT=54213
      - DOCKER_MODS=linuxserver/mods:transmission-floodui
    volumes:
      - transmission:/config
      - type: bind
        source: /media/shared
        target: /media/shared
    networks:
      - traefik-servicenet
      - yarr_internal
    ports:
      - 10.0.0.71:54213:54213
      - 10.0.0.71:54213:54213/udp
    labels:
      - traefik.enable=true
      - traefik.http.routers.transmission.entryPoints=https
      - traefik.http.routers.transmission.rule=Host(`transmission.fmlab.no`)
      - traefik.http.routers.transmission.service=transmission
      - traefik.http.routers.transmission.tls.certresolver=letsEncrypt
      - traefik.http.services.transmission.loadbalancer.server.port=9091
      - traefik.http.routers.transmission.middlewares=security@file
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - TZ=Europe/Oslo
      - PUID=2003
      - PGID=2003
    volumes:
      - sonarr:/config
      - type: bind
        source: /media/shared
        target: /media/shared
    networks:
      - traefik-servicenet
      - yarr_internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr.service=sonarr
      - traefik.http.routers.sonarr.entryPoints=https
      - traefik.http.routers.sonarr.tls.certresolver=letsEncrypt
      - traefik.http.routers.sonarr.rule=Host(`sonarr.fmlab.no`)
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
      - traefik.http.routers.sonarr.middlewares=security@file
    restart: unless-stopped
