version: "3.5"

networks:
  traefik-servicenet:
    external: true
    name: traefik-servicenet

services:
  homer:
    image: b4bz/homer:latest
    user: 2004:2004
    volumes:
      - ./config:/www/assets
    networks:
      - traefik-servicenet
    labels:
      - traefik.enable=true
      - traefik.http.routers.homer.entryPoints=https
      - traefik.http.routers.homer.rule=Host(`home.fmlab.no`)
      - traefik.http.routers.homer.service=homer
      - traefik.http.routers.homer.tls.certresolver=letsEncrypt
      - traefik.http.services.homer.loadbalancer.server.port=8080
      - traefik.http.routers.homer.middlewares=security@file
    restart: unless-stopped
