version: "3.5"

networks:
  traefik-servicenet:
    external: true
    name: traefik-servicenet

volumes:
  wireguard:

services:
  wg-easy:
    image: weejewel/wg-easy
    environment:
      - WG_DEFAULT_ADDRESS=10.100.0.x
      - WG_DEFAULT_DNS=1.1.1.1, 1.0.0.1
      - WG_HOST=vpn.fmlab.no
      - WG_MTU=1420 # 1500 - 80 (ipv6 overhead)
      - WG_PERSISTENT_KEEPALIVE=25
    volumes:
      - wireguard:/etc/wireguard
    ports:
      - 10.0.0.71:51820:51820/udp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - traefik-servicenet
    labels:
      - traefik.enable=true
      - traefik.http.routers.wireguard.entryPoints=https
      - traefik.http.routers.wireguard.rule=Host(`wireguard.fmlab.no`)
      - traefik.http.routers.wireguard.service=wireguard
      - traefik.http.routers.wireguard.tls.certresolver=letsEncrypt
      - traefik.http.services.wireguard.loadbalancer.server.port=51821
      - traefik.http.routers.wireguard.middlewares=security@file
    restart: unless-stopped
