global:
  sendAnonymousUsage: true

entryPoints:
  http:
    address: :8080
  https:
    address: :8443

certificatesResolvers:
  letsEncrypt:
    acme:
      email: "fredrickmyrvoll@gmail.com"
      storage: "/etc/traefik/acme/acme.json"
      httpChallenge:
        entryPoint: http

providers:
  docker:
    network: web
    exposedbydefault: false
    endpoint: "tcp://docker-proxy:2375"
  file:
    directory: "/etc/traefik/dynamic/"
    watch: true

api:
  dashboard: true

log:
  level: WARN

