version: '3.5'

networks:
  web:
    external: true
  internal:

services:
  traefik:
    container_name: traefik
    image: arm64v8/traefik:latest
    user: 1000:1000
    environment:
      - TZ=Europe/Oslo
    ports:
      - 8080:8080
      - 8443:8443
    networks:
      - web
      - internal
    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    labels:
      - autoheal=true
    volumes:
      - type: bind
        source: ${HOME}/.secrets/traefik/acme.json
        target: /etc/traefik/acme/acme.json
      - type: bind
        source: ${HOME}/.volumes/traefik/traefik.yml
        target: /etc/traefik/traefik.yml
      - type: bind
        read_only: true
        source: /etc/localtime
        target: /etc/localtime
      - type: bind
        source: ${HOME}/.volumes/traefik/dynamic/
        target: /etc/traefik/dynamic/
    depends_on:
      - docker-proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  docker-proxy:
    container_name: traefik_docker_proxy
    image: tecnativa/docker-socket-proxy:latest
    networks:
      - internal
    environment:
      - CONTAINERS=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
