---
- hosts: gateway
  become: true
  vars:
    dir_stack: /home/fredrick/Stacks

  tasks: 
    - name: traefik - craete stack dir
      file:
        path: "{{ dir_stack }}/{{ item }}"
        state: directory
        owner: fredrick
        group: fredrick
        mode: 0775
      loop:
        - system
        - system/traefik

    - name: traefik - create config dir
      ansible.builtin.file:
        path: /var/lib/homelab/traefik
        state: directory
        mode: 0755

    - name: traefik - pull image
      community.docker.docker_image:
        name: arm64v8/traefik:latest
        source: pull
        pull:
          platform: arm64 # linux/arm64/v8

    - name: copy - docker-compose.yml
      copy:
        src: ./docker-compose.yml
        dest: "{{ dir_stack }}/system/traefik/docker-compose.yml"

    - community.docker.docker_compose:
        project_src: "{{ dir_stack }}/system/traefik/docker-compose.yml"
        state: present
        restarted: true
      register: output

    - ansible.builtin.debug:
        var: output
