---
- hosts: all
  become: true
  max_fail_percentage: 0

  tasks:
    - name: apt - update & upgrade packages
      apt:
        upgrade: full
        update_cache: yes
        cache_valid_time: 3600
      register: package_upgrade

    - name: system - reboot (kernel update)
      reboot:
      when: package_upgrade.changed

    # Reboot should take place after configuring static ips in 1-config.yml
    # Else we will be stuck with no IP configuration
    - name: apt - remove packages
      apt:
        name: "{{ packages }}"
        state: absent
        autoremove: true
        purge: true
      vars:
        packages:
          - containerd
          - dhcpcd5
          - docker
          - docker-engine
          - docker.io
          - fake-hwclock
          - ifupdown
          - isc-dhcp-client
          - isc-dhcp-common
          - openresolv
          - runc

    - name: apt - download gpg key
      get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
      with_items:
        - url: https://download.docker.com/linux/debian/gpg
          dest: /usr/share/keyrings/docker.gpg.armored

    - name: apt - gpg dearmor key
      shell: "cat {{ item }}.armored | gpg --dearmor | tee {{ item }}"
      with_items:
        - /usr/share/keyrings/docker.gpg

    - name: apt - add repository
      apt_repository:
        repo: "{{ item.repo }}"
        state: present
        filename: "{{ item.filename }}"
      with_items:
        - repo: deb [arch=arm64 signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
          filename: docker.list

    - name: apt - install misc packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - ca-certificates
          - curl
          - gnupg
          - htop
          - nfs-kernel-server
          - nut
          - ufw

    - name: apt - install docker packages
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose
          - docker-compose-plugin
